"""samia.core.context_extension.primitives — the stable-prefix / tier-flow / phase-transition primitives.

Layer 1 (Owns / Depends):
    Owns:    Primitive B — stable-prefix anchoring (frozen_prefix_block, the FROZEN-tier
             MEMORY.md prefix cache); Primitive C — budget-aware tier flow
             (tier_flow_for_budget, the relevance/recency/Hebbian/access-count ranker
             that plans hot/warm tier moves under a token budget); Primitive D — the
             episodic→semantic phase transition (episodic_to_semantic_candidates, the
             connected-component clusterer that proposes mature episodic siblings for
             abstraction).
    Depends: the package config leaf (the budget default + episodic bars, np/json/hashlib,
             the aliased deps _ct/_tq/_vi/_dt, and the path/IO/vector helpers).

Layer 2 (What / Why):
    What: three budget-/lifecycle-oriented primitives that read the corpus and produce a
          block, a tier-move plan, or abstraction proposals — none of them retrieval, all
          of them lifecycle/structure.
    Why:  grouping the non-retrieval, non-replay primitives keeps each arm cohesive: the
          prefix cache and the tier-flow planner share the same frontmatter-read +
          token-estimate idioms, and the phase-transition clusterer reuses the same
          vector-index + chain-load helpers.
"""

from __future__ import annotations

from pathlib import Path

# Shared leaf — the budget default + episodic bars, np/json/hashlib, the aliased deps,
# and the path/IO/vector helpers.
from .config import (
    DEFAULT_BUDGET_TOKENS,
    EPISODIC_AGE_DAYS,
    EPISODIC_MIN_SIBLINGS,
    EPISODIC_SIM_THRESHOLD,
    hashlib,
    json,
    np,
    _dt,
    _ct,
    _tq,
    _vi,
    _nodes_dir,
    _chains_dir,
    _ctx_dir,
    _frozen_prefix_path,
    _tok_estimate,
    _node_text,
    _read_fm,
    _vi_manifest,
    _vi_embed,
)


# ---------------------------------------------------------------------------
# Primitive B — Stable-prefix anchoring (FROZEN tier)
# ---------------------------------------------------------------------------


def frozen_prefix_block(memory_dir: Path, write: bool = True) -> dict:
    nodes_dir = _nodes_dir(memory_dir)
    rows: list[tuple[str, str]] = []
    for p in sorted(nodes_dir.glob("*.md")):
        fm, body = _read_fm(p)
        tier = (fm.get("tier") or "").lower()
        if tier != "frozen":
            continue
        rows.append((p.name, f"# {fm.get('name', p.stem)}\n{body.strip()}\n"))

    if not rows:
        block = "<!-- no FROZEN nodes -->\n"
    else:
        sep = "\n\n---\n\n"
        block = (
            "<!-- frozen-prefix v1 :: do not edit, regenerated by "
            "memory_context_extension.py :: cache-stable -->\n"
            + sep.join(body for _, body in rows)
        )

    h = hashlib.sha256(block.encode("utf-8")).hexdigest()[:16]

    fpp = _frozen_prefix_path(memory_dir)
    if write:
        _ctx_dir(memory_dir).mkdir(parents=True, exist_ok=True)
        fpp.write_text(block, encoding="utf-8")

    return {
        "frozen_count": len(rows),
        "block_bytes": len(block.encode("utf-8")),
        "estimated_tokens": _tok_estimate(block),
        "sha256_16": h,
        "path": str(fpp) if write else None,
        "block": block,
    }


# ---------------------------------------------------------------------------
# Primitive C — Budget-aware tier flow
# ---------------------------------------------------------------------------


def tier_flow_for_budget(memory_dir: Path, query: str,
                         budget_tokens: int = DEFAULT_BUDGET_TOKENS,
                         dry_run: bool = True) -> dict:
    if not _vi_manifest(_vi, memory_dir).exists():
        return {"error": "no vector index"}
    nodes_dir = _nodes_dir(memory_dir)
    today = _dt.date.today()
    embeddings = np.load(_vi_embed(_vi, memory_dir))
    manifest = json.loads(_vi_manifest(_vi, memory_dir).read_text(encoding="utf-8"))
    entries = manifest.get("entries", {})

    qv = _vi._embed_batch([query])[0]
    sims = embeddings @ qv
    weights_path = memory_dir / "biomimetic" / "edge_weights.json"
    edge_w = {}
    if weights_path.exists():
        try:
            edge_w = json.loads(weights_path.read_text(encoding="utf-8"))
        except Exception:
            edge_w = {}
    hebb_count: dict[str, int] = {}
    for k in edge_w:
        a, b = k.split("::", 1)
        hebb_count[a] = hebb_count.get(a, 0) + 1
        hebb_count[b] = hebb_count.get(b, 0) + 1

    rows: list[dict] = []
    for rel, e in entries.items():
        p = nodes_dir / rel
        if not p.exists():
            continue
        fm, _ = _read_fm(p)
        tok, _ = _node_text(p)
        la = _tq.parse_date(fm.get("last_access"))
        days_ago = (today - la).days if la else 365
        recency = max(0.0, 1.0 - min(days_ago, 365) / 365.0)
        try:
            ac = int(fm.get("access_count") or "0")
        except Exception:
            ac = 0
        ac_norm = min(1.0, np.log1p(ac) / 5.0)
        hd = min(1.0, hebb_count.get(rel, 0) / 8.0)
        rel_score = float(sims[e["row"]]) if e.get("row") is not None else 0.0
        score = 0.55 * max(0.0, rel_score) + 0.20 * recency + \
                0.15 * hd + 0.10 * ac_norm
        rows.append({"node": rel, "tokens": tok, "score": round(score, 4),
                     "current_tier": fm.get("tier", "warm")})

    rows.sort(key=lambda r: -r["score"])

    plan: list[dict] = []
    spent = 0
    for r in rows:
        new_tier = "hot" if spent + r["tokens"] <= budget_tokens else "warm"
        if new_tier != r["current_tier"]:
            plan.append({**r, "new_tier": new_tier})
        if new_tier == "hot":
            spent += r["tokens"]

    if not dry_run:
        for change in plan:
            p = nodes_dir / change["node"]
            fm_lines, body = _tq.read_node(p)
            fm_lines = _tq.fm_set(fm_lines, "tier", change["new_tier"])
            _tq.write_node(p, fm_lines, body)

    return {"budget_tokens": budget_tokens, "spent_tokens": spent,
            "changes": plan, "dry_run": dry_run, "ranked_count": len(rows)}


# ---------------------------------------------------------------------------
# Primitive D — Episodic→semantic phase transition
# ---------------------------------------------------------------------------


def episodic_to_semantic_candidates(memory_dir: Path,
                                    chain: str | None = None) -> dict:
    if not _vi_manifest(_vi, memory_dir).exists():
        return {"error": "no vector index"}

    nodes_dir = _nodes_dir(memory_dir)
    chains_dir = _chains_dir(memory_dir)
    embeddings = np.load(_vi_embed(_vi, memory_dir))
    manifest = json.loads(_vi_manifest(_vi, memory_dir).read_text(encoding="utf-8"))
    entries = manifest.get("entries", {})

    today = _dt.date.today()
    chains_to_scan = [chain] if chain else _ct.list_chains(chains_dir)

    proposals: list[dict] = []
    for cname in chains_to_scan:
        try:
            cd = _ct.load_chain(chains_dir, cname)
        except (SystemExit, FileNotFoundError):
            continue
        members = cd.get("members") or []
        rows = []
        for m in members:
            f = m.get("file") if isinstance(m, dict) else None
            if not f:
                continue
            stem = Path(f).name
            if stem not in entries:
                continue
            p = nodes_dir / stem
            if not p.exists():
                continue
            fm, _ = _read_fm(p)
            vf = _tq.parse_date(fm.get("valid_from"))
            if not vf or (today - vf).days < EPISODIC_AGE_DAYS:
                continue
            row_idx = entries[stem]["row"]
            rows.append((stem, vf, row_idx, m.get("addr")))
        if len(rows) < EPISODIC_MIN_SIBLINGS:
            continue
        idxs = [r[2] for r in rows]
        emb = embeddings[idxs]
        sims = emb @ emb.T
        n = len(rows)
        adj = [[i for i in range(n) if i != j and sims[i, j] >= EPISODIC_SIM_THRESHOLD]
               for j in range(n)]
        seen: set[int] = set()
        for start in range(n):
            if start in seen:
                continue
            stack = [start]
            comp: list[int] = []
            while stack:
                k = stack.pop()
                if k in seen:
                    continue
                seen.add(k)
                comp.append(k)
                for nb in adj[k]:
                    if nb not in seen:
                        stack.append(nb)
            if len(comp) < EPISODIC_MIN_SIBLINGS:
                continue
            avg_sim = float(np.mean([sims[i, j] for i in comp for j in comp if i != j]))
            proposals.append({
                "chain": cname,
                "nodes": [rows[i][0] for i in comp],
                "addrs": [rows[i][3] for i in comp],
                "earliest": min(rows[i][1] for i in comp).isoformat(),
                "avg_similarity": round(avg_sim, 3),
                "rationale": (f"{len(comp)} episodic nodes >="
                              f"{EPISODIC_AGE_DAYS}d old, "
                              f"avg cosine {avg_sim:.2f} ≥ {EPISODIC_SIM_THRESHOLD}"),
            })
    return {"proposals": proposals, "count": len(proposals)}


# --------------------------------------------------------------------------
# [Asthenosphere] samia.core.context_extension.primitives
# Author:     code_warrior
# Project:    Asthenosphere — SAM/IA
# Version:    1.0.0
# Phase:      Primitives B / C / D — stable-prefix anchoring, budget-aware tier flow,
#             episodic→semantic phase transition.
#             + Phase-B modularization (carved from the monolith, ZERO behavior change).
# Layer:      core (pure library, no daemon dependency)
# Role:       the non-retrieval, non-replay lifecycle/structure primitives.
# Stability:  stable.
# ErrorModel: fail-soft — a missing vector index returns {"error": ...}; per-node read
#             errors and a corrupt edge_weights.json are swallowed; tier_flow is dry-run
#             by default (no writes until dry_run=False).
# Depends:    .config (budget default + episodic bars, np/json/hashlib, _ct/_tq/_vi/_dt,
#             the path/IO/vector helpers).
# Exposes:    frozen_prefix_block, tier_flow_for_budget, episodic_to_semantic_candidates.
# Lines:      266
# --------------------------------------------------------------------------
